// docsfn/svelte/src/ChangelogEntry.svelte
<script lang="ts">
  import type { BlogPost } from "@docsfn/core/browser";
  import DatedCollectionEntry from "./DatedCollectionEntry.svelte";

  export let post: BlogPost;
  export let collectionLabel = "Changelog";
  export let collectionHref = "/changelog";
  export let embedded = false;
  export let showBackLink = true;
</script>

<DatedCollectionEntry
  {post}
  {collectionLabel}
  {collectionHref}
  {embedded}
  {showBackLink}
>
  <slot />
</DatedCollectionEntry>

// docsfn/react/src/ChangelogEntry.tsx
import React, { type ReactNode } from "react";
import type { BlogPost } from "@docsfn/core";
import { DatedCollectionEntry } from "./DatedCollectionEntry";

export interface ChangelogEntryProps {
  post: BlogPost;
  children: ReactNode;
  collectionLabel?: string;
  collectionHref?: string;
  embedded?: boolean;
  showBackLink?: boolean;
}

export function ChangelogEntry({
  post,
  children,
  collectionLabel = "Changelog",
  collectionHref = "/changelog",
  embedded = false,
  showBackLink = true,
}: ChangelogEntryProps) {
  return (
    <DatedCollectionEntry
      post={post}
      collectionLabel={collectionLabel}
      collectionHref={collectionHref}
      embedded={embedded}
      showBackLink={showBackLink}
    >
      {children}
    </DatedCollectionEntry>
  );
}
