// docsfn/react/src/ChangelogList.tsx
import React from "react";
import type { BlogPost } from "@docsfn/core";
import { DatedCollectionList } from "./DatedCollectionList";

export interface ChangelogListProps {
  posts: BlogPost[];
  title?: string;
  description?: string;
  embedded?: boolean;
  emptyLabel?: string;
  getPostHref?: (post: BlogPost) => string;
}

export function ChangelogList({
  posts,
  title = "Changelog",
  description = "Product updates and release notes.",
  embedded = false,
  emptyLabel = "No changelog entries yet.",
  getPostHref,
}: ChangelogListProps) {
  return (
    <DatedCollectionList
      posts={posts}
      title={title}
      description={description}
      embedded={embedded}
      emptyLabel={emptyLabel}
      ariaLabel={title}
      getPostHref={getPostHref}
    />
  );
}

// docsfn/svelte/src/ChangelogList.svelte
<script lang="ts">
  import type { BlogPost } from "@docsfn/core/browser";
  import DatedCollectionList from "./DatedCollectionList.svelte";

  export let posts: BlogPost[] = [];
  export let title = "Changelog";
  export let description: string | undefined = "Product updates and release notes.";
  export let embedded = false;
  export let emptyLabel = "No changelog entries yet.";
  export let getPostHref: ((post: BlogPost) => string) | undefined = undefined;
</script>

<DatedCollectionList
  {posts}
  {title}
  {description}
  {embedded}
  {emptyLabel}
  ariaLabel={title}
  {getPostHref}
/>
